services:
  db:
    image: postgres
    container_name: ifc-db-i.db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
    driver: local